# Flash cards: full Spanish class vocabulary
# -*- coding: utf-8 -*-

cards = [
    [ "Es necesario", "It's necessary" ],
    [ "dar", "to give" ],
    [ "Es importante", "It's important" ],
    [ "Es posible", "It's possible" ],
    [ "usar", "to use" ],
    [ "Es imposible", "It's impossible" ],
    [ "hablar", "to speak" ],
    [ "Es fácil", "It's easy" ],
    [ "trabajar", "to work" ],
    [ "Es difícil", "It's difficult" ],
    [ "practicar", "to practice" ],

    [ "Me gustaría", "I would like" ],
    [ "pagar", "to pay, pay for" ],
    [ "Quiero", "I want" ],
    [ "ayudar", "to help" ],
    [ "Quiere", "He/she/you/it wants" ],
    [ "estudiar", "to study" ],
    [ "Tengo que", "I must, have to" ],
    [ "llenar", "to fill out" ],
    [ "Tiene que", "He/she/you/it must" ],
    [ "comprar", "to buy" ],

    [ "casa", "house" ],
    [ "puerta",	"door" ],
    [ "ventana", "window" ],
    [ "mesa", "table" ],
    [ "silla", "chair" ],
    [ "cocina", "kitchen" ],
    [ "luz", "light" ],
    [ "ducha", "shower" ],
    [ "alcoba", "bedroom" ],

    [ "Puedo",          "I can" ],
    [ "Favor de",	"Kindly, please" ],
    [ "Fui a",          "I went to" ],
    [ "Fue a",          "He, she, it, you went to" ],
    [ "Voy a",          "I'm going to" ],
    [ "Va a",           "He, she, it, you are going to" ],

    [ "-lo, e.g. hacerlo", "it" ],

    [ "regresar", "return" ],
    [ "jugar", "play"],
    [ "empujar", "push" ],
    [ "firmar", "sign" ],
    [ "tomar", "drink" ],
    [ "visitar", "visit" ],
    [ "llevar", "carry, wear" ],
    [ "llamar", "to call" ],
    [ "arreglar", "fix" ],
    [ "La playa", "The beach" ],
    [ "La ola", "The wave" ],
    [ "La banca", "The bench" ],
    [ "La familia", "The family" ],
    [ "La pelota", "The ball" ],
    [ "La muchacha", "The young girl" ],
    [ "La mujer", "The woman" ],
    [ "La bicicleta", "The bicycle" ],
    [ "La soda", "The soda" ],
    [ "La cerveza", "The beer" ],

    [ "hay", "there is, are" ],
    [ "no hay", "there isn't, aren't" ],
    [ "aqui", "here" ],
    [ "alli", "there" ],
    [ "arriba", "upstairs, up" ],

    [ "hola", "hello" ],
    [ "qué tal?", "what's up?" ],
    [ "qué pasa?", "what's happening?" ],
    [ "como esta usted?", "how are you?" ],
    [ "como se llama usted?",  "what's your name?" ],
    [ "Buenos días", "Good day" ],
    [ "Buenos tardes", "Good afternoon" ],
    [ "Buenos nochas", "Good evening" ],

    [ "uno", "one" ],
    [ "dos", "two" ],
    [ "tres", "three" ],
    [ "cuatro", "four" ],
    [ "cinco", "five" ],
    [ "seis", "six" ],
    [ "siete", "seven" ],
    [ "ocho", "eight" ],
    [ "nueve", "nine" ],
    [ "dies", "ten" ],

    [ "ciudad", "city" ],
    [ "calle", "street" ],
    [ "iglesia", "church" ],
    [ "escuela", "school" ],
    [ "maquina", "machine" ],
    [ "fabrica", "factory" ],
    [ "biblioteca", "library" ],
    [ "fabrica", "factory" ],
    [ "tienda", "store" ],
    [ "farmacia", "pharmacy" ],
    [ "cuarto", "room" ],
    [ "teléfono", "telephone" ],
    [ "baño", "bathroom" ],
    [ "el agua", "water" ],
    [ "piso", "floor" ],
    [ "bote", "trashcan" ],
    [ "cama", "bed" ],
    [ "toalla", "towel" ],
    [ "tina", "tub" ],

    [ "el lunes", "Monday" ],
    [ "el martes", "Tuesday" ],
    [ "el miercoles", "Wednesday" ],
    [ "el jueves", "Thursday" ],
    [ "el viernes", "Friday" ],
    [ "el sabado", "Saturday" ],
    [ "el domingo", "Sunday" ],

    [ "el arbol", "tree" ],
    [ "el camino", "road", ],

    [ "Sé", "I know how"],
    [ "Estoy para", "I'm about"],
    [ "Pienso", "I plan"],
    [ "Después de", "After"],
    [ "Antes de", "Before"],
    [ "Acabo de", "I have just"],

    [ "primo, prima", "cousin" ],
    [ "sobrino, sobrina", "nephew, niece" ],
    [ "nieto, nieta", "grandson, g-daughter" ],
    [ "abuelo, abuela", "grandfather, mother" ],
    [ "hijo, hija", "son, daughter" ],
    [ "tio, tia", "uncle, aunt" ],
    [ "hermano, hermana", "brother, sister" ],

    [ "yo", "I" ],
    [ "usted", "you" ],
    [ "el", "he" ],
    [ "ella", "she" ],
    [ "su", "your" ],

    [ "derecho", "straight ahead" ],
    [ "a la izquierda", "to the left" ],
    [ "a la derecha", "to the right" ],

    [ "almuerzo", "lunch" ],
    [ "desayuno", "breakfast" ],
    [ "almuerzo", "lunch" ],
    [ "cena", "supper" ],
    [ "comida", "food" ],
    [ "camerero", "waiter" ],
    [ "cuenta", "bill" ],
    [ "cuento", "story" ],
    [ "langosta", "lobster" ],
    [ "ensalada", "salad" ],
    [ "comer", "to eat" ],
    [ "ordenar", "to order" ],
    [ "pagar", "to pay" ],    
    [ "tambien", "also" ],
    [ "este, esta", "this one" ],
    [ "ese, esa", "that one" ],
    [ "hoy", "today" ],

    [ "?donde esta?", "where is?" ],
    [ "en", "in, on" ],
    [ "esta", "is, it is (for health or location)" ],
    [ "es", "is, it is (not health or location)" ],

    [ "pequeña", "small" ],
    [ "bonita", "pretty" ],
    [ "fea", "ugly" ],
    [ "buena", "good" ],
    [ "mala", "bad" ],
    [ "caro", "expensive" ],
    [ "gordo", "fat" ],
    [ "grande", "big" ],
    [ "amable", "kind" ],
    [ "flaco", "skinny" ],
    [ "simpática", "nice" ],
    [ "rojo", "red" ],
    [ "azul", "blue" ],
    [ "verde", "green" ],
    [ "amarillo", "yellow" ],
    [ "gris", "grey" ],
    [ "negro", "black" ],
    [ "anaranjado", "orange" ],
    [ "mucho", "a lot" ],
    [ "dulce", "sweet" ],
    [ "caliente", "hot" ],
    [ "viejo", "old" ],
    [ "joven", "young" ],
    [ "sucio", "dirty" ],
    [ "pardo", "brown" ],
    [ "rosado", "pink" ],
    [ "veinte", "20 " ],
    [ "treinta", "30 " ],
    [ "cuarenta", "40" ],
    [ "cincuenta", "50" ],
    [ "sesenta", "60" ],
    [ "setenta", "70" ],
    [ "ochenta", "80" ],
    [ "noventa", "90" ],
    [ "cien(to)", "100" ],
    [ "dólares", "dollars" ],

    [ "¿Que hora es?", "What time is it?"],
    [ "son las", "it is [time other than 1:00]"],
    [ "y media", "and half an hour"],
    [ "y cuarto", "and a quarter hour"],

    [ "enero", "January"],
    [ "febrero", "February"],
    [ "marzo", "March"],
    [ "abril", "April"],
    [ "mayo", "May"],
    [ "junio", "June"],
    [ "julio", "July"],
    [ "agosto", "August"],
    [ "septiembre", "September"],
    [ "octubre", "October"],
    [ "noviembre", "November"],
    [ "diciembre", "December"],

    [ "¿Qué tiempo hace?", "What's the weather like?"],
    [ "hace calor", "it's hot"],
    [ "hace frio", "it's cold"],
    [ "hace sol", "it's sunny"],
    [ "hace viento", "it's windy"],
    [ "Las estaciones del año", "The seasons of the year"],
    [ "el otoño", "the fall"],
    [ "el invierno", "the winter"],
    [ "la primavera", "the spring"],
    [ "el verano", "the summer"],
    [ "no va", "it doesn't work"],
    [ "no funciona", "it doesn't work"],
    [ "perdón", "excuse me"],
    [ "ahora mismo", "right now"],
    [ "ir", "to go"],
    [ "venir", "to come"],

    [ "mucho gusto", "nice to meet you, much pleasure"],
    [ "Igualmente", "(response to 'mucho gusto')" ],

    [ "se cae en pedazos", "it's falling apart" ],
    [ "¿Cómo se llama usted?", "What's your name?" ],
    [ "Me llamo XXX", "My name is XXX" ],
    [ "Con permiso", "excuse me (to get someone's attention)" ],
    [ "Perdón", "Pardon" ],
    [ "Lo siento", "I'm sorry" ],
    [ "¿Puedo pasar?", "Can I pass?" ],

    [ "aeropuerto", "airport" ],
    [ "avion", "airplane" ],
    [ "vuelo", "flight" ],
    [ "pasaporte", "passport" ],
    [ "autobús", "bus" ],       
    [ "sirviente", "attendant" ],
    [ "letrero", "sign" ],       
    [ "gasolina", "gasoline" ],
    [ "aceite", "oil" ],       
    [ "llantas", "tires" ],
    [ "radiador", "radiator" ],
    [ "escape", "leak" ],      
    [ "llega", "arrives" ],
    [ "llegar", "to arrive" ],
    [ "sale", "leaves" ],     
    [ "salir", "to leave" ],
    [ "ganga", "bargain" ], 
    [ "bastante", "enough" ],
    [ "el cuartel de policia", "the police station" ],
    [ "el estacion de policia", "the police station" ],
    [ "la tarjeta de credito", "the credit card" ],
    [ "pasar", "to pass" ],
    [ "revisar", "to check" ],
    [ "mostrar", "to show" ],
    [ "hacer", "to do, to make" ],
    [ "traducir", "to translate" ],
    [ "llegar", "to arrive" ],
    [ "salir", "to leave" ],
    [ "aprender", "to learn" ],
    [ "empezar", "to begin" ],
    [ "decir", "to tell" ],
    [ "facturar", "to check (luggage)" ],
    [ "estoy perdido", "I'm lost" ],
    [ "vamonos", "let's go" ],
    [ "cuanto es?", "how much is it?" ],
    [ "a donde va?", "where are you going?" ],
    [ "esta lejos", "it's far" ],
    [ "como no?", "why not?  of course"],
    [ "a sus ordenes", "at your service" ],
    [ "esta tomando el pelo", "you're teasing" ],
    [ "voy y vengo", "I'll be right back (I go and I come)" ],
    [ "equipaje", "luggage" ],
    [ "otra vez", "again" ],
    [ "aduana", "customs" ],
    [ "billete", "ticket" ],
    [ "ver", "to see" ],
    [ "alto", "stop, high" ],
    [ "cedo al paso", "yield" ],
    [ "circulacion", "one way" ],
    [ "despacio", "slow" ],
    [ "desviacion", "detour" ],
    [ "no rebase", "no passing" ],
    [ "coche", "car" ],
    [ "carro", "car" ],
    [ "el escape", "a leak" ],
    [ "comodo", "comfortable" ],
    [ "matricula", "registration" ],
    [ "licencia", "license" ],
    [ "seguir", "to follow" ],
    [ "limite", "limit" ],

    [ "conmigo",  "with me" ],
    [ "con nosotros", "with us" ],
    [ "contigo", "with you (familiar)" ],
    [ "con usted", "with you (formal)" ],
    [ "con ustedes", "with you (plural)" ],
    [ "con el", "with him" ],              
    [ "con ellos", "with them, masculine or mixed" ],
    [ "con ella", "with her" ],
    [ "con ellas", "with them" ],

    [ "siempre", "always" ],
    [ "el pelo largo", "long hair" ],
    [ "los ojos", "the eyes" ],      
    [ "tampoco", "neither, either" ],
    [ "Â¡calmese!", " be quiet" ],
    [ "no se preocupe", "don't worry" ],
    [ "los estados unidos", "the United States" ],
    [ "la broma", "a joke" ],                     
    [ "siempre", "always" ],

    [ "tengo/tiene", "I have, you, he, she, it has" ],
    [ "tengo prisa", "I'm in a hurry" ],
    [ "tengo razón", "I'm right" ],
    [ "tengo sed", "I'm thirsty" ],
    [ "tengo hambre", "I'm hungry" ],
    [ "tengo calor", "I'm hot" ],
    [ "tengo frio", "I'm cold" ],

    [ "?Por que?", "why?" ],
    [ "?Quien?", "who?" ],  
    [ "?Qué?", "What?" ],
    [ "?Dónde?", "Where?"],
    [ "?Cuando?", "When?" ],

    [ "yo", "I" ],
    [ "usted (formal)", "you" ],
    [ "tu (familiar)", "you" ],
    [ "ustedes", "you all" ],
    [ "nosotros", "we" ],
    [ "ellos", "they (masculine or mixed group" ],
    [ "ellas", "they (feminine group" ],
    [ "el", "he" ],                      
    [ "ella", "she" ],
    [ "ellos, ellas", "they" ],

    [ "pregunta", "question" ],

    [ "el cuerpo", "body" ],
    [ "el pelo ", "hair " ],
    [ "la cabeza ", "head " ],
    [ "el ojo ", "eye " ],
    [ "la nariz ", "nose " ],
    [ "la oreja", "ear" ],   
    [ "la boca", "mouth" ],
    [ "el brazo", "arm" ], 
    [ "la mano", "hand" ],
    [ "el pecho", "chest" ],
    [ "la pierna", "leg" ], 
    [ " el estómago ", "stomach" ],
    [ "el dedo", "toe or finger" ], 

    [ "la clinica", "doctor's office" ],
    [ "me duele", "I hurt, I ache - me duele la cabeza" ],
    [ "la enfermera", "nurse (f)" ],                      
    [ "la doctora", "doctor (f)" ], 
    [ "malo", "ill, bad" ],        
    [ "enfermo", "sick" ], 
    [ "debil", "weak" ],  
    [ "nervioso", "nervous" ],
    [ "contento", "happy" ],  
    [ "deprimido", "depressed" ],
    [ "enjoada", "angry, mad" ], 
    [ "triste", "sad" ],        
    [ "cansado", "tired" ],
    [ "limpiar", "to clean" ],
    [ "dolor", "pain" ],      
    [ "el resfrio", "a cold" ],
    [ "la bruja", "a witch, witch doctor (f)" ],

    [ "planchar", "to press, to iron" ],        
    [ "lavar", "to wash" ],             
    [ "traer ", "to bring" ],
    [ "secar", "to dry" ],   

    [ "ropa", "clothes" ],
    [ "blusa", "blouse" ],
    [ "camisa", "shirt" ],
    [ "chaqueta", "jacket" ],
    [ "bufanda", "scarf" ],  
    [ "falda", "skirt" ],  
    [ "medias", "stockings" ],
    [ "cinturón", "belt" ],  
    [ "vestido", "dress" ], 
    [ "pantalones", "pants" ],
    [ "el traje", "the suit" ],
    [ "los zapatos", "shoes" ],
    [ "los calcetines", "socks" ],
    [ "la gorra", "the hat" ],    

    [ "muy bien", "very well" ],
    [ "Asi-asi", "so-so" ],
    [ "Mas o menos", "so- so" ],
    [ "nos vemos", "see you" ],
    [ "maleta", "suitcase" ],  

    [ "solo", "just" ],
    [ "creer", "to believe" ],
    [ "yo creo", "I believe" ],
    [ "temprano", "early" ],
    [ "cartera", "wallet" ],
    [ "cajero", "bank teller" ],
    [ "que", "that" ],
    [ "no se ", "I don't know" ],
    [ "si", "if" ],
    [ "me dijo que", "told me that" ],
    [ "abrir", "to open" ],
    [ "que es el tipo de cambio?", "what is the rate of exchange?" ],
    [ "cambiar", "to change" ],
    [ "los cheques de viajeros", "traveler's checks" ],
    [ "todo el tiempo", "all the time" ],
    [ "a propósito", "by the way" ],
    [ "sentarse", "to sit down" ],
    [ "quedarse", "to stay" ],
    [ "dormir", "to sleep" ],
    [ "acostarse", "to go to bed" ],
    [ "despertarse", "to wake up" ],
    [ "entrar", "to enter" ],
    [ "llegar", "to arrive" ],
    [ "contestar", "to answer" ],
    [ "seguirme", "to follow me" ],
    [ "favor de pasar", "please come in" ],
    [ "quiere pasar?", "do you want to come in?" ],
    [ "favor de sentarse", "please sit down" ],
    [ "Puedo sentarme?", "Can I sit down?" ],
    [ "antes que nada", "before anything else" ],
    [ "oye", "listen" ],
    [ "arquitectura", "architecture" ],
    [ "un peso", "100 centavos" ],
    [ "esposo,esposa", "husband, wife" ],
    [ "buena suerte", "good luck" ],

    [ "dentista", "dentist" ],
    [ "taxista", "taxi driver" ],
    [ "maestro, a", "teacher" ],
    [ "mecanico, a", "mechanic" ],
    [ "criado,a", "servant" ],
    [ "cocinero,a", "cook" ],
    [ "gerente", "manager" ],
    [ "cliente", "client" ],
    [ "jefe, patrón",  "boss" ],
    [ "estudiante", "student" ],
    [ "trabajador de fabrica", "factory worker" ],

    [ "negocio", "business" ],
    [ "cada hora", "each hour" ],
    [ "trabajo", "job, work" ],
    [ "afuera", "outside" ],
    [ "escoba", "broom" ],
    [ "martillo", "hammer" ],

    [ "yo soy", "I am" ],
    [ "discúlpeme", "excuse me" ],
    [ "¿cuanta cobra?", "how much do you charge?" ],
    [ "cobra", "charge" ],
    [ "me gusta", "I like" ],
    [ "¿que hace?", "what do you do?" ],
    [ "estacionamiento", "parking lot" ],
    [ "esta contratado, a", "you're hired" ],
    [ "le gusta", "likes (he, she)" ],

    [ "usar la cocina", "cook, use the kitchen" ],
    [ "usar este", "use this (one)" ],            

    [ "manejar", "to drive" ],
    [ "loco, a", "crazy" ],
    [ "platero", "silversmith" ],
    [ "carro, coche, vehiculo", "car" ],
    [ "mis", "my, for plurals" ],
    [ "sus", "your, for plurals" ],
    [ "favor de no ir", "please don't go" ],
    [ "nunca", "never" ],
    [ "siempre", "always" ],
    [ "algo", "something" ],
    [ "nada", "nothing" ],
    [ "Ella no tiene nada", "She doesn't have anything" ],
    [ "alguien", "somebody" ],
    [ "nadie", "nobody" ],
    [ "pero", "but" ],
    [ "digame", "talk to me (as 'hello' on phone" ],
    [ "recado", "message" ],
    [ "conchas", "shells" ],
    [ "arena", "sand" ],
    [ "sonido", "sound" ],
    [ "este tipo", "this kind" ],
    [ "conductor, a", "driver" ],
    [ "muchas veces", "many times" ],
    [ "la lana", "money" ],
    [ "habla", "speaking, he, she it, speaks" ],
    [ "regresa", "returning" ],
    [ "¿como?", "what?" ],
    [ "mentira", "lie" ],
    [ "ayer", "yesterday" ],
    [ "quizás", "perhaps" ],
    [ "se murió", "died" ],
    [ "tener", "to have" ],
    [ "manejar", "to drive" ],
    [ "carretera", "highway" ],
    [ "otra vez", "again" ],
    [ "caña", "fishing pole" ],
    [ "pez/pescado", "fish" ],
    [ "lugar", "place" ],
    [ "tiburones", "sharks" ],
    [ "aletas", "fins" ],
    [ "mascara", "mask" ],
    [ "veterinario", "veterinarian" ],
    [ "tabla", "board" ],
    [ "pescar", "to fish" ],
    [ "nadar", "to swim" ],
    [ "tampoco/tambien", "neither/also" ],
    [ "es peligroso", "it's dangerous" ],
    [ "que baboso, a/ que bruto", "what an idiot" ],
    [ "despiértese", "wake up" ],
    [ "está en paz", "is at peace" ],
    [ "vayase", "get going" ],
    [ "qué extraño", "how strange" ],
    [ "mismo", "same" ],
    [ "tan pronto como posible", "as soon as possible" ],
    [ "carretera", "highway" ],

]
